//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProviders.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataProviders.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 154.979710017787,10.1151980739623,230.775285176243,0.351088978190444,1.21321852505712,0.0277600868175552,0.497783590526219
        ///43.7369801587132,8.70849154876009,56.4375315161409,0.337967173266205,0.528914390130513,0.038367403456181,0.401827338478448
        ///125.668034220891,7.60554157365372,170.919079697378,0.296445586049561,0.912028898484693,0.0263959102269243,0.378946418910728
        ///50.8275529047603,8.44427634190967,101.050375216444,0.141108204854672,0.011680702556796,0.0337671717879209,0.246802804035508
        ///137.1583912974 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string pricing_data_inputs {
            get {
                return ResourceManager.GetString("pricing_data_inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 15.8868050113588
        ///1.53272103707823
        ///4.55152199281026
        ///1.16611554794775
        ///0.162013314687293
        ///0.540720736683099
        ///4.08333356720085
        ///1.90840650508932
        ///1.16973386039917
        ///1.91713258310158
        ///0.315191758353482
        ///0.799351858290795
        ///1.21877141177781
        ///3.87177112920266
        ///4.83517105679455
        ///3.86901202077132
        ///0.989619455538767
        ///0.560827213330912
        ///9.94142469027134
        ///6.80301177912436
        ///2.16556075086078
        ///9.20602125992922
        ///0.174911017542094
        ///6.22581266940795
        ///2.98670948405919
        ///6.91791938183765
        ///0.146741151692654
        ///11.3958565984946
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string pricing_data_outputs {
            get {
                return ResourceManager.GetString("pricing_data_outputs", resourceCulture);
            }
        }
    }
}
